### ISSUE TITLE
Error running RPI Monitor

### ISSUE THREAD

**Issue by FJGAlemany** [Woersty/LoxBerry-Plugin-RPi-Monitor#13]
Hi,

I have installed this plugin in Loxberry version 2.0.1.3. When I run the plugin I get the following error.

**Software error:**
Can't call method "param" on an undefined value at /opt/loxberry/webfrontend/htmlauth/plugins/rpi_monitor/index.cgi line 100.
For help, please send mail to the webmaster ([no address given]), giving this error message and the time and date of the error.

Are there some specific configuration to do before run plugin?

**Comment by Woersty** [comment]
I guess there is an issue with the language.
Will check tomorrow.
Had the same issue in other plugins, too.

**Comment by Woersty** [comment]
Solved in 2020.03.22

**Comment by FJGAlemany** [comment]
Thanks!!!!
