### ISSUE TITLE
RPI opens frame in Frame 

### ISSUE THREAD

**Issue by bayoda** [Woersty/LoxBerry-Plugin-RPi-Monitor#16]
Hi 
Actually RPI doesn't open itself but opens as frame in frame - not opening the rpi in last version. 
Was an automatic Update  any ideas? 

Greetings 
Mike

**Comment by Woersty** [comment]
You don't have to use the Admin Page but the plugin page.
Http://Loxberry/plugins/rpi_monitor

(Was the same in previous versions)

**Comment by bayoda** [comment]
Reinstalled - now it opens as before with all the goodies...    (click in loxberry on the icon worked before)
