### ISSUE TITLE
RPi-Monitor Plugin -> "ramlog voll"

### ISSUE THREAD

**Issue by Noschvie** [Woersty/LoxBerry-Plugin-RPi-Monitor#20]
Siehe Forum :
https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/242152-ramlog-voll?p=300705#post300705

**Comment by Noschvie** [comment]
Workaround: RPIMonitor Plugin deinstallieren.

**Comment by Woersty** [comment]
Ich gucke mal, ob ich das Logging ausschalten kann.￼
Ich selbst benutze das Plugin gar nicht mehr￼.

**Comment by Woersty** [comment]
Naja eher Workaround Plugin richtig konfigurieren. Logging nicht aus = Logging an.
Egal. Ich habe es geändert. Ab sofort ist alles unter Loglevel Debug beim RPI Monitor = Logging aus und bei Debug ist es an.

**Comment by Noschvie** [comment]
Habe nun Version 2021.06.14 installiert
![grafik](https://user-images.githubusercontent.com/48217146/121974721-4e69da00-cd80-11eb-8e41-2172ffe6b761.png)
Thanks!

**Comment by Noschvie** [comment]
... Version 2021.06.14 seit einigen Tagen im Einatz und RAM-Disk unauffällig.
@Woersty : Danke nochmals!
