### ISSUE TITLE
Update der Packages

### ISSUE THREAD

**Issue by scharrin2** [Woersty/LoxBerry-Plugin-RPi-Monitor#3]
Hallo,

nach der Installation wurde mir angezeigt, welches Skript man ausführen muss, um die Pakete anzeigen zu lassen, welche aktualisiert werden können.

Ich habe dazu das erste Skript ausgeführt (wahrscheinlich aktualisiert dies nur einmalig).

Nach der einmaligen Aktualisierung wird mir nicht mehr angezeigt, wie die beiden anderen Kommandos zur Installation heißen.

Kannst Du mir diese nochmal nennen bzw. wo kann ich diese nachschauen?

Viele Grüße,
Christian

**Comment by Woersty** [comment]
Du kannst das automatisch prüfen lassen:
/etc/init.d/rpimonitor install_auto_package_status_update
Abschalten mit:
/etc/init.d/rpimonitor remove_auto_package_status_update

**Comment by Woersty** [comment]
Nachtrag: Normalerweise sollte er das bei der aktuellen Plugin-Version automatisch installieren.

**Comment by scharrin2** [comment]
Hallo,

ja - sorry, hab's gesehen.

Was mir noch aufgefallen ist:
Nach dem Update der Pakete steht in der Übersicht 0 upgradeable(s). Wenn ich aber mit der Maus auf die Lupe "fahre", werden mir die 48 Pakete angezeigt, welche ich vorher aktualisiert habe.

Viele Grüße,
Christian

**Comment by scharrin2** [comment]
<img width="1116" alt="bildschirmfoto 2016-09-20 um 18 07 28" src="https://cloud.githubusercontent.com/assets/22325491/18678684/217ecbd4-7f5d-11e6-80ed-64d7cc309eb5.png">

**Comment by Woersty** [comment]
Let's see what Xavier thinks. :+1:

**Comment by scharrin2** [comment]
Hallo,

jetzt funktioniert das Scrollen und man kann die Bereiche WiFi und Memory komplett sehen.

Was nicht so schön ist, dass es zwei Scrollbars gibt - aber das ist ja zweitrangig.

Viele Grüße,
Christian
<img width="1280" alt="bildschirmfoto 2016-09-20 um 20 03 33" src="https://cloud.githubusercontent.com/assets/22325491/18682645/5ba65678-7f6d-11e6-911f-0c429dabd883.png">

**Comment by scharrin2** [comment]
Hallo Woersty,

nach einem Neustart des Raspberry (sudo reboot) sieht es wieder so aus:

<img width="1201" alt="bildschirmfoto 2016-09-20 um 20 23 28" src="https://cloud.githubusercontent.com/assets/22325491/18683412/72c57458-7f70-11e6-9e0c-6e42e324514f.png">

Viele Grüße,
Christian

**Comment by Woersty** [comment]
Das Problem mit der Anzeige wird hier behandelt https://github.com/XavierBerger/RPi-Monitor/issues/118

**Comment by Woersty** [comment]
@scharrin2: Das mit dem `/etc/init.d/rpimonitor install_auto_package_status_update` hast du versucht?

**Comment by scharrin2** [comment]
Ja - mittlerweile funktioniert es (auch nach einem Neustart).
Ich kann aber nicht mehr genau sagen, woran es gelegen hat.
