### ISSUE TITLE
VM Image

### ISSUE THREAD

**Issue by Shogun1978** [Woersty/LoxBerry-Plugin-RPi-Monitor#4]
Kann man eventuell auch die Stats der VM abfragen? Ist zwar nur bedingt hilfreich, aber vielleicht mag es der ein oder andere doch nutzen. Ich habe es mit dem neuesten VM-Image 0.2.2, bekomme aber eine Fehlermeldung.

**Comment by Woersty** [comment]
Leider nicht, da das RPi-Monitor-Tool für den Raspberry Pi geschrieben wurde.
Außerdem zeige ich das nur an. Das Plugin macht praktisch nichts.
Wenn, dann müsste Xavier das machen:  https://github.com/XavierBerger/RPi-Monitor-deb/

**Comment by Shogun1978** [comment]
Ok, schade... vielleicht schaue ich mir mal dein Plugin ab, um herauszufinden, wie du die Daten abrufst. Vielleicht kann ich das mit Debian-Bordmitteln ergänzen und umsetzen. Aber danke für den Tip!
