### ISSUE TITLE
Fehlermeldung bei dem Plugin

### ISSUE THREAD

**Issue by wick0310** [Woersty/LoxBerry-Plugin-RPi-Monitor#5]
Hallo ich bekomme immer eine fehlermeldung beim öffnen des Plugin

das ist das logfile kann mir da jemand helfen ?

<INFO> Starte Plugin-Installation
<OK> Plugin-Archiv erfolgreich hochgeladen
<INFO> Extrahiere Plugin-Archiv
<INFO> Command: /usr/bin/unzip -d /tmp/uploads/L3LTGEvwLJ /tmp/uploads/L3LTGEvwLJ/L3LTGEvwLJ.zip
Archive:  /tmp/uploads/L3LTGEvwLJ/L3LTGEvwLJ.zip
a64ebdd81ca7ff78174f7b62ba82be6cc8bf220c
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/LICENSE  
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/README.md  
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/apt  
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/config/
 extracting: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/config/RPi-Monitor.cfg  
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/daemon/
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/daemon/daemon  
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/data/
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/data/data.conf  
 extracting: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/data/rpimonitor_latest_all.deb  
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/data/version.conf  
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/icons/
 extracting: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/icons/icon_128.png  
 extracting: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/icons/icon_256.png  
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/icons/icon_512.png  
 extracting: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/icons/icon_64.png  
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/plugin.cfg  
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/postinstall.sh  
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/postupgrade.sh  
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/preinstall.sh  
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/preupgrade.sh  
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/de/
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/de/help.html  
 extracting: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/de/language.dat  
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/de/settings.html  
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/en/
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/en/help.html  
 extracting: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/en/language.dat  
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/en/settings.html  
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/uninstall/
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/uninstall/uninstall  
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/webfrontend/
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/webfrontend/cgi/
  inflating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/webfrontend/cgi/index.cgi  
   creating: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/webfrontend/html/
 extracting: /tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/webfrontend/html/index.php  
<OK> Plugin-Archiv erfolgreich entpackt
<INFO> Author:    Christian Woerstenfeld
<INFO> Email:     git@loxberry.woerstenfeld.de
<INFO> Version:   0.6
<INFO> Name:      RPi-Monitor
<INFO> Folder:    rpi_monitor
<INFO> Title:     RPi-Monitor
<INFO> Interface: 1.0
<OK> Alle Konfigurationsparameter vorhanden
<INFO> Plugin ist bereits installiert -> Upgrade wird durchgefÃ¼hrt
<INFO> Starte Skript PREUPGRADE
<INFO> Command: /bin/sh "/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/preupgrade.sh" "L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master" "RPi-Monitor" "rpi_monitor" "0.6" "/opt/loxberry"
<INFO> Creating temporary folders for upgrading
mkdir: cannot create directory '/tmp/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master_upgrade': No such file or directory
mkdir: cannot create directory '/tmp/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master_upgrade/config': No such file or directory
mkdir: cannot create directory '/tmp/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master_upgrade/log': No such file or directory
<INFO> Backing up existing config files
cp: cannot create directory '/tmp/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master_upgrade/config': No such file or directory
<INFO> Backing up existing log files
cp: cannot create directory '/tmp/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master_upgrade/log': No such file or directory
<OK> Skript ohne Fehler ausgefÃ¼hrt
<INFO> Deinstalliere alte Installation
<INFO> Starte Skript PREINSTALL
<INFO> Command: /bin/sh "/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/preinstall.sh" "L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master" "RPi-Monitor" "rpi_monitor" "0.6" "/opt/loxberry"
<INFO> Nothing to do here.
<OK> Skript ohne Fehler ausgefÃ¼hrt
<INFO> Installiere Konfigurationsdateien
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/config/RPi-Monitor.cfg' -> '/opt/loxberry/config/plugins/rpi_monitor/RPi-Monitor.cfg'
<OK> Alle Dateien erfolgreich installiert
<INFO> Installiere Templatedateien
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/de/help.html' -> '/opt/loxberry/templates/plugins/rpi_monitor/de/help.html'
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/de/language.dat' -> '/opt/loxberry/templates/plugins/rpi_monitor/de/language.dat'
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/de/settings.html' -> '/opt/loxberry/templates/plugins/rpi_monitor/de/settings.html'
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/en/help.html' -> '/opt/loxberry/templates/plugins/rpi_monitor/en/help.html'
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/en/language.dat' -> '/opt/loxberry/templates/plugins/rpi_monitor/en/language.dat'
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/templates/en/settings.html' -> '/opt/loxberry/templates/plugins/rpi_monitor/en/settings.html'
<OK> Alle Dateien erfolgreich installiert
<INFO> Installiere DAEMON
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/daemon/daemon' -> '/opt/loxberry/system/daemons/plugins/RPi-Monitor'
<OK> Alle Dateien erfolgreich installiert
<INFO> Setze Berechtigungen: /bin/chmod 755 /opt/loxberry/system/daemons/plugins/RPi-Monitor
<OK> Berechtigungen erfolgreich gesetzt
<INFO> Installiere Daten-Dateien
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/data/data.conf' -> '/opt/loxberry/data/plugins/rpi_monitor/data.conf'
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/data/rpimonitor_latest_all.deb' -> '/opt/loxberry/data/plugins/rpi_monitor/rpimonitor_latest_all.deb'
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/data/version.conf' -> '/opt/loxberry/data/plugins/rpi_monitor/version.conf'
<OK> Alle Dateien erfolgreich installiert
<INFO> Installiere CGI-Dateien
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/webfrontend/cgi/index.cgi' -> '/opt/loxberry/webfrontend/cgi/plugins/rpi_monitor/index.cgi'
<OK> Alle Dateien erfolgreich installiert
<INFO> Setze Berechtigungen: /bin/chmod -R 755 /opt/loxberry/webfrontend/cgi/plugins/rpi_monitor/
<OK> Berechtigungen erfolgreich gesetzt
<INFO> Installiere HTML-Dateien
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/webfrontend/html/index.php' -> '/opt/loxberry/webfrontend/html/plugins/rpi_monitor/index.php'
<OK> Alle Dateien erfolgreich installiert
<INFO> Installiere Icons
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/icons/icon_128.png' -> '/opt/loxberry/webfrontend/html/system/images/icons/rpi_monitor/icon_128.png'
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/icons/icon_256.png' -> '/opt/loxberry/webfrontend/html/system/images/icons/rpi_monitor/icon_256.png'
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/icons/icon_512.png' -> '/opt/loxberry/webfrontend/html/system/images/icons/rpi_monitor/icon_512.png'
'/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/icons/icon_64.png' -> '/opt/loxberry/webfrontend/html/system/images/icons/rpi_monitor/icon_64.png'
<OK> Icons konnten erfolgreich installiert werden
<INFO> Aktualisiere APT-Paketdatenbank
<INFO> Command: /usr/bin/sudo /usr/bin/apt-get -q -y update
Get:1 http://mirrordirector.raspbian.org jessie InRelease [14.9 kB]
Get:2 http://archive.raspberrypi.org jessie InRelease [13.2 kB]
Get:3 http://archive.raspberrypi.org jessie/main armhf Packages [117 kB]
Get:4 http://mirrordirector.raspbian.org jessie/main armhf Packages [8981 kB]
Hit https://deb.nodesource.com jessie InRelease
Hit https://deb.nodesource.com jessie/main Sources
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Hit https://deb.nodesource.com jessie/main armhf Packages
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Get:5 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:6 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:7 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:8 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:9 https://deb.nodesource.com jessie/main Translation-en [162 B]
Ign https://deb.nodesource.com jessie/main Translation-en
Get:10 http://mirrordirector.raspbian.org jessie/contrib armhf Packages [37.5 kB]
Get:11 http://mirrordirector.raspbian.org jessie/non-free armhf Packages [70.3 kB]
Get:12 http://mirrordirector.raspbian.org jessie/rpi armhf Packages [1356 B]
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Fetched 9235 kB in 17s (538 kB/s)
Reading package lists...
<OK> APT-Paketdatenbank wurde erfolgreich aktualisiert
<INFO> Installiere zusÃ¤tzliche Software-Pakete
<INFO> Command: /usr/bin/sudo /usr/bin/apt-get -q -y install  dpkg-dev librrds-perl libhttp-daemon-perl libjson-perl libipc-sharelite-perl libfile-which-perl
Reading package lists...
Building dependency tree...
Reading state information...
libfile-which-perl is already the newest version.
libfile-which-perl set to manually installed.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 dpkg-dev : Depends: libdpkg-perl (= 1.17.27) but it is not going to be installed
            Recommends: build-essential but it is not going to be installed
            Recommends: fakeroot but it is not going to be installed
            Recommends: libalgorithm-merge-perl but it is not going to be installed
 librrds-perl : Depends: librrd4 (>= 1.4~rc2) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
<ERROR> Paket konnte nicht installiert werden
<INFO> Aktualisiere APT-Paketdatenbank
<INFO> Command: /usr/bin/sudo /usr/bin/apt-get -q -y update
Hit http://archive.raspberrypi.org jessie InRelease
Hit http://mirrordirector.raspbian.org jessie InRelease
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Hit https://deb.nodesource.com jessie InRelease
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Hit https://deb.nodesource.com jessie/main Sources
Hit https://deb.nodesource.com jessie/main armhf Packages
Get:1 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:2 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:3 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:4 https://deb.nodesource.com jessie/main Translation-en [162 B]
Get:5 https://deb.nodesource.com jessie/main Translation-en [162 B]
Ign https://deb.nodesource.com jessie/main Translation-en
Reading package lists...
<OK> APT-Paketdatenbank wurde erfolgreich aktualisiert
<INFO> Command: /usr/bin/sudo /usr/bin/apt-get -q -y install  dpkg-dev librrds-perl libhttp-daemon-perl libjson-perl libipc-sharelite-perl libfile-which-perl
Reading package lists...
Building dependency tree...
Reading state information...
libfile-which-perl is already the newest version.
libfile-which-perl set to manually installed.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 dpkg-dev : Depends: libdpkg-perl (= 1.17.27) but it is not going to be installed
            Recommends: build-essential but it is not going to be installed
            Recommends: fakeroot but it is not going to be installed
            Recommends: libalgorithm-merge-perl but it is not going to be installed
 librrds-perl : Depends: librrd4 (>= 1.4~rc2) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
<ERROR> Paket konnte nicht installiert werden
<INFO> Starte Skript POSTINSTALL
<INFO> Command: /bin/sh "/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/postinstall.sh" "L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master" "RPi-Monitor" "rpi_monitor" "0.6" "/opt/loxberry"
<INFO> ******************************************
<INFO> * Please reboot to start the RPi-Monitor *
<INFO> ******************************************
<INFO> * Bitte mache einen Neustart des Systems.*
<INFO> ******************************************
<OK> Skript ohne Fehler ausgefÃ¼hrt
<INFO> Starte Skript POSTUPGRADE
<INFO> Command: /bin/sh "/tmp/uploads/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master/postupgrade.sh" "L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master" "RPi-Monitor" "rpi_monitor" "0.6" "/opt/loxberry"
<INFO> Copy back existing config files
cp: cannot stat '/tmp/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master_upgrade/config/rpi_monitor/*': No such file or directory
<INFO> Copy back existing log files
cp: cannot stat '/tmp/L3LTGEvwLJ/LoxBerry-Plugin-RPi-Monitor-master_upgrade/log/rpi_monitor/*': No such file or directory
<OK> Skript ohne Fehler ausgefÃ¼hrt
<INFO> Aktualisiere SystemmenÃ¼s
<OK> SystemmenÃ¼s aktualisert
<INFO> RÃ¤ume auf und lÃ¶sche temporÃ¤re Dateien

**Comment by Woersty** [comment]
Also zuerst gibt es ein Problem im Upgrade Script. Da muss ich mal schauen.
Und dann hat dein System unaufgelöste Abhängigkeiten:
```
pkg-dev : Depends: libdpkg-perl (= 1.17.27) but it is not going to be installed
Recommends: build-essential but it is not going to be installed
Recommends: fakeroot but it is not going to be installed
Recommends: libalgorithm-merge-perl but it is not going to be installed
librrds-perl : Depends: librrd4 (>= 1.4rc2) but it is not going to be installed
Try 'apt-get -f install' ...

```
Was genau geht denn nicht?

**Comment by wick0310** [comment]
Hallo sorry das ich mir erst jetzt melde also ich kann das plugin nicht mal aufmachen bekkomme sofort eine fehlermeldung 
![rpi monitor](https://cloud.githubusercontent.com/assets/22304429/21326839/b27c6586-c62c-11e6-87cc-12a7127748a9.PNG)

**Comment by Woersty** [comment]
LoxBerry nochmal neu gestartet und einige Zeit gewartet? Manchmal dauert das...

**Comment by wick0310** [comment]
Ja habe ich schon gemacht auch schon mal vom Strom genommen aber hat alles nichts gebracht

**Comment by wick0310** [comment]
Habe jetzt auch noch andere Browser versucht doch bei allen das gleiche
