### ISSUE TITLE
Plugin bringt nur leeren Bildschirm

### ISSUE THREAD

**Issue by scharrin2** [Woersty/LoxBerry-Plugin-RPi-Monitor#7]
Seit dem letzten Update des Raspberry (sudo apt-get update & sudo apt-get upgrade) bleibt die Seite des RPi-Monitor ohne irgendeine Fehlermeldung leer.

Woran könnte das liegen?
![bildschirmfoto 2017-08-03 um 21 02 52](https://user-images.githubusercontent.com/22325491/28938722-3835223e-788f-11e7-98b6-206fb80f9305.png)

**Comment by Woersty** [comment]
Ab v2018.3.4 für LoxBerry 1.0.3+ geht es bei mir
